name: GCP deploy

on:
  push:
    branches:
      - main
      
permissions:
    id-token: write
    contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - uses: 'google-github-actions/auth@v2'
      with:
        # credentials_json: '${{ secrets.GCP }}' # Replace with the name of your GitHub Actions secret.
        workload_identity_provider: 'projects/892056173251/locations/global/workloadIdentityPools/identity-pool-example/providers/github-provider'
        service_account: 'app-696@precise-equator-459106-n3.iam.gserviceaccount.com'
    
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: '>= 363.0.0'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - run: gcloud app deploy
